# Generated by Django 2.2.3 on 2019-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourstravel', '0003_auto_20190808_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(),
        ),
    ]
